### PR TITLE
Fix fefe TLS

### PR DESCRIPTION
**Pull request by Turakar**
I tried HTTPS on Fefe before, but it seems like java does not trust LetsEncrypt certificates by default. Therefore this PR contains the certificate (pushed using ssh over git protocol) as a java keystore which gets loaded on initialization. The fefe plugin had to be rewritten to use java's way of doing HTTPS connections for this.

Please squash the commits once merging them, as they're a mess.

### CODE REVIEW

**Comment by rleh** [comment]
What is inside _src/main/resources/fefe.keystore_?
How can I open this '*.keystore' with openssl?

**Comment by rleh** [comment]
Ok, it is a _Java KeyStore_.
I can open it using javas _keytool_:

```
keytool -list -v -keystore fefe.keystore
```

**Review by rleh — DISMISSED** [review]
Using the current certificate from _blog.fefe.de_ is a bad idea, because this certificate will expire in December.

Instead you should put Letsencrypts CA certificate in the keystore, because this is the certificate _blog.fefe.de_s certificate is signed by.
The [Letsencrypts CA certificate](https://letsencrypt.org/certificates/) you need is [this](https://letsencrypt.org/certs/isrgrootx1.pem).

```
$ keytool -list -v -keystore fefe.keystore | grep Valid
Enter keystore password:  fefefe
Valid from: Fri Sep 09 16:26:00 CEST 2016 until: Thu Dec 08 15:26:00 CET 2016
```

**Comment by Turakar** [comment]
I've changed the certificate to the one of the ISRG and of the letsencrypt authority. This grants us support until 2021. Normally I would not have to include the intermediate certficate of Let's Encrypt authority, but Fefe does not seem to send intermediate certificates as it should do in theory.

**Review by rleh — APPROVED** [review]
Great :+1:

**Comment by rleh** [comment]
Du warst wohl schneller :smile:

**Comment by Turakar** [comment]
:smile:

**Pull request merged**
